"""empty message

Revision ID: 2696d0016c29
Revises: 
Create Date: 2016-12-01 13:38:06.055872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2696d0016c29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('fips', sa.String(), nullable=True),
    sa.Column('cand', sa.String(), nullable=True),
    sa.Column('st', sa.String(), nullable=True),
    sa.Column('votes', sa.BigInteger(), nullable=True),
    sa.Column('total_votes', sa.BigInteger(), nullable=True),
    sa.Column('lead', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('us_elections')
    # ### end Alembic commands ###
