"""empty message

Revision ID: 8046805b5e41
Revises: 2696d0016c29
Create Date: 2016-12-01 13:49:29.891851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8046805b5e41'
down_revision = '2696d0016c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_elections', sa.Column('votos', sa.BigInteger(), nullable=True))
    op.drop_column('us_elections', 'votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_elections', sa.Column('votes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('us_elections', 'votos')
    # ### end Alembic commands ###
